"""
Opening name helpers: ECO code lookup + move-based detection fallback.
"""
import chess
import chess.pgn

# ---------------------------------------------------------------------------
# ECO code → opening name  (covers the most common codes in each range)
# ---------------------------------------------------------------------------
ECO_NAMES: dict[str, str] = {
    # A — Flank / English / Dutch / other d4
    "A00": "Irregular Opening",
    "A01": "Nimzovich-Larsen Attack",
    "A02": "Bird's Opening",
    "A03": "Bird's Opening",
    "A04": "Réti Opening",
    "A05": "Réti Opening",
    "A06": "Réti Opening",
    "A07": "King's Indian Attack",
    "A08": "King's Indian Attack",
    "A09": "Réti Opening",
    "A10": "English Opening",
    "A11": "English, Caro-Kann Defence",
    "A12": "English, Caro-Kann Defence",
    "A13": "English Opening",
    "A14": "English Opening",
    "A15": "English, Anglo-Indian",
    "A16": "English Opening",
    "A17": "English Opening",
    "A18": "English, Mikenas-Carls",
    "A19": "English, Mikenas-Carls, Sicilian",
    "A20": "English, Reversed Sicilian",
    "A21": "English Opening",
    "A22": "English Opening",
    "A23": "English, Bremen, Keres",
    "A24": "English, Bremen with g3",
    "A25": "English, Closed",
    "A26": "English, Closed",
    "A27": "English, Three Knights",
    "A28": "English, Four Knights",
    "A29": "English, Four Knights, Kingside Fianchetto",
    "A30": "English, Symmetrical",
    "A31": "English, Symmetrical, Benoni",
    "A32": "English, Symmetrical",
    "A33": "English, Symmetrical",
    "A34": "English, Symmetrical",
    "A35": "English, Symmetrical",
    "A36": "English, Symmetrical",
    "A37": "English, Symmetrical, Fianchetto",
    "A38": "English, Symmetrical",
    "A39": "English, Symmetrical, Main line",
    "A40": "Queen's Pawn Opening",
    "A41": "Old Indian Defence",
    "A42": "Modern Defence, Averbakh",
    "A43": "Benoni, Old Benoni",
    "A44": "Old Benoni Defence",
    "A45": "Queen's Pawn Game",
    "A46": "Queen's Pawn, Torre Attack",
    "A47": "Queen's Indian Defence",
    "A48": "King's Indian, London System",
    "A49": "King's Indian, Fianchetto",
    "A50": "Queen's Pawn Game",
    "A51": "Budapest Gambit Declined",
    "A52": "Budapest Gambit",
    "A53": "Old Indian Defence",
    "A54": "Old Indian, Ukrainian Variation",
    "A55": "Old Indian Defence",
    "A56": "Benoni Defence",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit Accepted",
    "A59": "Benko Gambit",
    "A60": "Benoni Defence",
    "A61": "Benoni Defence",
    "A62": "Benoni, Fianchetto",
    "A63": "Benoni, Fianchetto",
    "A64": "Benoni, Fianchetto",
    "A65": "Benoni, King's Pawn Line",
    "A66": "Benoni, Pawn Storm",
    "A67": "Benoni, Taimanov",
    "A68": "Benoni, Four Pawns Attack",
    "A69": "Benoni, Four Pawns Attack, Main Line",
    "A70": "Benoni, Classical",
    "A71": "Benoni, Classical",
    "A72": "Benoni, Classical",
    "A73": "Benoni, Classical, Main Line",
    "A74": "Benoni, Classical, Main Line",
    "A75": "Benoni, Classical, Czech Variation",
    "A76": "Benoni, Classical, 9...Re8",
    "A77": "Benoni, Classical, 9...Re8 10.Nd2",
    "A78": "Benoni, Classical, 9...Re8 10.Nd2 Na6",
    "A79": "Benoni, Classical, 9...Re8 10.Nd2 Na6 11.f3",
    "A80": "Dutch Defence",
    "A81": "Dutch Defence",
    "A82": "Dutch, Staunton Gambit",
    "A83": "Dutch, Staunton Gambit",
    "A84": "Dutch Defence",
    "A85": "Dutch with c4 & Nc3",
    "A86": "Dutch, Leningrad",
    "A87": "Dutch, Leningrad, Main Variation",
    "A88": "Dutch, Leningrad, Main Variation with c6",
    "A89": "Dutch, Leningrad, Main Variation with Nc6",
    "A90": "Dutch Defence",
    "A91": "Dutch Defence",
    "A92": "Dutch Defence",
    "A93": "Dutch, Stonewall",
    "A94": "Dutch, Stonewall with Ba3",
    "A95": "Dutch, Stonewall",
    "A96": "Dutch, Classical Variation",
    "A97": "Dutch, Ilyin-Zhenevsky",
    "A98": "Dutch, Ilyin-Zhenevsky, Nimzovich",
    "A99": "Dutch, Ilyin-Zhenevsky, Main Line",

    # B — Sicilian, Caro-Kann, Pirc, Modern
    "B00": "Uncommon King's Pawn Opening",
    "B01": "Scandinavian Defence",
    "B02": "Alekhine's Defence",
    "B03": "Alekhine's Defence",
    "B04": "Alekhine's Defence, Modern",
    "B05": "Alekhine's Defence, Modern",
    "B06": "Modern Defence",
    "B07": "Pirc Defence",
    "B08": "Pirc, Classical",
    "B09": "Pirc, Austrian Attack",
    "B10": "Caro-Kann Defence",
    "B11": "Caro-Kann, Two Knights",
    "B12": "Caro-Kann Defence",
    "B13": "Caro-Kann, Exchange Variation",
    "B14": "Caro-Kann, Panov-Botvinnik",
    "B15": "Caro-Kann Defence",
    "B16": "Caro-Kann, Bronstein-Larsen",
    "B17": "Caro-Kann, Steinitz Variation",
    "B18": "Caro-Kann, Classical",
    "B19": "Caro-Kann, Classical, Main Line",
    "B20": "Sicilian Defence",
    "B21": "Sicilian, Grand Prix Attack",
    "B22": "Sicilian, Alapin",
    "B23": "Sicilian, Closed",
    "B24": "Sicilian, Closed",
    "B25": "Sicilian, Closed",
    "B26": "Sicilian, Closed, 6.Be3",
    "B27": "Sicilian Defence",
    "B28": "Sicilian, O'Kelly",
    "B29": "Sicilian, Nimzovich-Rubinstein",
    "B30": "Sicilian, Nimzovich-Rossolimo",
    "B31": "Sicilian, Nimzovich-Rossolimo, Fianchetto",
    "B32": "Sicilian Defence",
    "B33": "Sicilian, Sveshnikov",
    "B34": "Sicilian, Accelerated Dragon",
    "B35": "Sicilian, Accelerated Dragon",
    "B36": "Sicilian, Accelerated Dragon, Maróczy Bind",
    "B37": "Sicilian, Accelerated Dragon, Maróczy Bind",
    "B38": "Sicilian, Accelerated Dragon, Maróczy Bind",
    "B39": "Sicilian, Accelerated Dragon, Maróczy Bind",
    "B40": "Sicilian Defence",
    "B41": "Sicilian, Kan (Paulsen)",
    "B42": "Sicilian, Kan, 5.Bd3",
    "B43": "Sicilian, Kan, 5.Nc3",
    "B44": "Sicilian, Taimanov",
    "B45": "Sicilian, Taimanov",
    "B46": "Sicilian, Taimanov",
    "B47": "Sicilian, Taimanov",
    "B48": "Sicilian, Taimanov",
    "B49": "Sicilian, Taimanov, 6.Be2",
    "B50": "Sicilian Defence",
    "B51": "Sicilian, Canal-Sokolsky Attack",
    "B52": "Sicilian, Canal-Sokolsky Attack",
    "B53": "Sicilian, Chekhover",
    "B54": "Sicilian, Dragon",
    "B55": "Sicilian, Prins, Venice Attack",
    "B56": "Sicilian Defence",
    "B57": "Sicilian, Sozin",
    "B58": "Sicilian, Classical",
    "B59": "Sicilian, Classical, Boleslavsky",
    "B60": "Sicilian, Richter-Rauzer",
    "B61": "Sicilian, Richter-Rauzer",
    "B62": "Sicilian, Richter-Rauzer",
    "B63": "Sicilian, Richter-Rauzer",
    "B64": "Sicilian, Richter-Rauzer",
    "B65": "Sicilian, Richter-Rauzer",
    "B66": "Sicilian, Richter-Rauzer",
    "B67": "Sicilian, Richter-Rauzer",
    "B68": "Sicilian, Richter-Rauzer",
    "B69": "Sicilian, Richter-Rauzer, 7.Qd2 Main Line",
    "B70": "Sicilian, Dragon",
    "B71": "Sicilian, Dragon, Levenfish",
    "B72": "Sicilian, Dragon",
    "B73": "Sicilian, Dragon, Classical",
    "B74": "Sicilian, Dragon, Classical",
    "B75": "Sicilian, Dragon, Yugoslav Attack",
    "B76": "Sicilian, Dragon, Yugoslav Attack",
    "B77": "Sicilian, Dragon, Yugoslav Attack",
    "B78": "Sicilian, Dragon, Yugoslav Attack",
    "B79": "Sicilian, Dragon, Yugoslav Attack, 9.Bc4",
    "B80": "Sicilian, Scheveningen",
    "B81": "Sicilian, Scheveningen, Keres Attack",
    "B82": "Sicilian, Scheveningen",
    "B83": "Sicilian, Scheveningen",
    "B84": "Sicilian, Scheveningen, Classical",
    "B85": "Sicilian, Scheveningen, Classical",
    "B86": "Sicilian, Sozin Attack",
    "B87": "Sicilian, Sozin, Flank",
    "B88": "Sicilian, Sozin",
    "B89": "Sicilian, Sozin",
    "B90": "Sicilian, Najdorf",
    "B91": "Sicilian, Najdorf, Zagreb",
    "B92": "Sicilian, Najdorf, 6.Be2",
    "B93": "Sicilian, Najdorf, 6.f4",
    "B94": "Sicilian, Najdorf, 6.Bg5",
    "B95": "Sicilian, Najdorf, 6.Bg5",
    "B96": "Sicilian, Najdorf, 6.Bg5",
    "B97": "Sicilian, Najdorf, 6.Bg5",
    "B98": "Sicilian, Najdorf, 6.Bg5",
    "B99": "Sicilian, Najdorf, Main Line",

    # C — French, open e4 e5
    "C00": "French Defence",
    "C01": "French, Exchange",
    "C02": "French, Advance",
    "C03": "French, Tarrasch",
    "C04": "French, Tarrasch, Guimard Main Line",
    "C05": "French, Tarrasch",
    "C06": "French, Tarrasch",
    "C07": "French, Tarrasch, Open",
    "C08": "French, Tarrasch, Open",
    "C09": "French, Tarrasch, Open, Main Line",
    "C10": "French Defence",
    "C11": "French Defence",
    "C12": "French, MacCutcheon",
    "C13": "French, Classical",
    "C14": "French, Classical",
    "C15": "French, Winawer",
    "C16": "French, Winawer",
    "C17": "French, Winawer",
    "C18": "French, Winawer, Advance",
    "C19": "French, Winawer, Advance, Main Line",
    "C20": "King's Pawn Game",
    "C21": "Centre Game",
    "C22": "Centre Game",
    "C23": "Bishop's Opening",
    "C24": "Bishop's Opening",
    "C25": "Vienna Game",
    "C26": "Vienna Game",
    "C27": "Vienna Game",
    "C28": "Vienna Game",
    "C29": "Vienna Gambit",
    "C30": "King's Gambit",
    "C31": "King's Gambit Declined, Falkbeer",
    "C32": "King's Gambit Declined, Falkbeer",
    "C33": "King's Gambit Accepted",
    "C34": "King's Gambit Accepted",
    "C35": "King's Gambit Accepted, Cunningham",
    "C36": "King's Gambit Accepted, Abbazia Defence",
    "C37": "King's Gambit Accepted, Quaade",
    "C38": "King's Gambit Accepted",
    "C39": "King's Gambit Accepted, Allgaier",
    "C40": "King's Knight Opening",
    "C41": "Philidor Defence",
    "C42": "Petrov's Defence",
    "C43": "Petrov, Modern Attack",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Game",
    "C47": "Four Knights Game",
    "C48": "Four Knights, Spanish",
    "C49": "Four Knights, Double Spanish",
    "C50": "Italian Game",
    "C51": "Italian, Evans Gambit",
    "C52": "Italian, Evans Gambit",
    "C53": "Italian, Giuoco Piano",
    "C54": "Italian, Giuoco Piano",
    "C55": "Italian, Two Knights",
    "C56": "Italian, Two Knights",
    "C57": "Italian, Two Knights",
    "C58": "Italian, Two Knights",
    "C59": "Italian, Two Knights, Main Line",
    "C60": "Ruy Lopez",
    "C61": "Ruy Lopez, Bird's Defence",
    "C62": "Ruy Lopez, Old Steinitz",
    "C63": "Ruy Lopez, Schliemann",
    "C64": "Ruy Lopez, Classical",
    "C65": "Ruy Lopez, Berlin Defence",
    "C66": "Ruy Lopez, Berlin Defence",
    "C67": "Ruy Lopez, Berlin, Rio de Janeiro",
    "C68": "Ruy Lopez, Exchange",
    "C69": "Ruy Lopez, Exchange, Gligoric",
    "C70": "Ruy Lopez",
    "C71": "Ruy Lopez, Modern Steinitz",
    "C72": "Ruy Lopez, Modern Steinitz",
    "C73": "Ruy Lopez, Modern Steinitz",
    "C74": "Ruy Lopez, Modern Steinitz",
    "C75": "Ruy Lopez, Modern Steinitz",
    "C76": "Ruy Lopez, Modern Steinitz",
    "C77": "Ruy Lopez, Morphy Defence",
    "C78": "Ruy Lopez, Archangel",
    "C79": "Ruy Lopez, Steinitz Defence Deferred",
    "C80": "Ruy Lopez, Open",
    "C81": "Ruy Lopez, Open, Howell Attack",
    "C82": "Ruy Lopez, Open",
    "C83": "Ruy Lopez, Open, Classical",
    "C84": "Ruy Lopez, Closed",
    "C85": "Ruy Lopez, Exchange",
    "C86": "Ruy Lopez, Worrall Attack",
    "C87": "Ruy Lopez, Closed",
    "C88": "Ruy Lopez, Closed",
    "C89": "Ruy Lopez, Marshall",
    "C90": "Ruy Lopez, Closed",
    "C91": "Ruy Lopez, Closed",
    "C92": "Ruy Lopez, Closed",
    "C93": "Ruy Lopez, Closed, Smyslov",
    "C94": "Ruy Lopez, Closed, Breyer",
    "C95": "Ruy Lopez, Closed, Breyer",
    "C96": "Ruy Lopez, Closed",
    "C97": "Ruy Lopez, Chigorin",
    "C98": "Ruy Lopez, Chigorin",
    "C99": "Ruy Lopez, Chigorin, Main Line",

    # D — Queen's Gambit, Slav, Grünfeld
    "D00": "Queen's Pawn Game",
    "D01": "Richter-Veresov Attack",
    "D02": "Queen's Pawn Game",
    "D03": "Torre Attack",
    "D04": "Queen's Pawn Game",
    "D05": "Queen's Pawn, Colle System",
    "D06": "Queen's Gambit",
    "D07": "Queen's Gambit Declined, Chigorin",
    "D08": "Queen's Gambit Declined, Albin Counter-Gambit",
    "D09": "Queen's Gambit Declined, Albin Counter-Gambit",
    "D10": "Slav Defence",
    "D11": "Slav Defence",
    "D12": "Slav Defence",
    "D13": "Slav, Exchange",
    "D14": "Slav, Exchange, Anti-Moscow",
    "D15": "Slav Defence",
    "D16": "Slav Defence",
    "D17": "Slav Defence",
    "D18": "Slav, Dutch",
    "D19": "Slav, Dutch, Main Line",
    "D20": "Queen's Gambit Accepted",
    "D21": "Queen's Gambit Accepted",
    "D22": "Queen's Gambit Accepted, Alekhine Defence",
    "D23": "Queen's Gambit Accepted",
    "D24": "Queen's Gambit Accepted with Nc3",
    "D25": "Queen's Gambit Accepted, Janowski-Larsen",
    "D26": "Queen's Gambit Accepted",
    "D27": "Queen's Gambit Accepted, Classical",
    "D28": "Queen's Gambit Accepted, Classical",
    "D29": "Queen's Gambit Accepted, Classical Main Line",
    "D30": "Queen's Gambit Declined",
    "D31": "Queen's Gambit Declined",
    "D32": "Queen's Gambit Declined, Tarrasch",
    "D33": "Queen's Gambit Declined, Tarrasch",
    "D34": "Queen's Gambit Declined, Tarrasch",
    "D35": "Queen's Gambit Declined",
    "D36": "Queen's Gambit Declined, Exchange",
    "D37": "Queen's Gambit Declined",
    "D38": "Queen's Gambit Declined, Ragozin",
    "D39": "Queen's Gambit Declined, Ragozin, Vienna",
    "D40": "Queen's Gambit Declined, Semi-Tarrasch",
    "D41": "Queen's Gambit Declined, Semi-Tarrasch",
    "D42": "Queen's Gambit Declined, Semi-Tarrasch",
    "D43": "Semi-Slav Defence",
    "D44": "Semi-Slav Defence",
    "D45": "Semi-Slav Defence",
    "D46": "Semi-Slav Defence",
    "D47": "Semi-Slav, Meran",
    "D48": "Semi-Slav, Meran, Reynolds",
    "D49": "Semi-Slav, Meran, Main Line",
    "D50": "Queen's Gambit Declined",
    "D51": "Queen's Gambit Declined",
    "D52": "Queen's Gambit Declined",
    "D53": "Queen's Gambit Declined",
    "D54": "Queen's Gambit Declined, Anti-Neo-Orthodox",
    "D55": "Queen's Gambit Declined",
    "D56": "Queen's Gambit Declined",
    "D57": "Queen's Gambit Declined, Lasker Defence",
    "D58": "Queen's Gambit Declined, Tartakower",
    "D59": "Queen's Gambit Declined, Tartakower, Main Line",
    "D60": "Queen's Gambit Declined, Orthodox",
    "D61": "Queen's Gambit Declined, Orthodox",
    "D62": "Queen's Gambit Declined, Orthodox, Rubinstein",
    "D63": "Queen's Gambit Declined, Orthodox",
    "D64": "Queen's Gambit Declined, Orthodox, Rubinstein",
    "D65": "Queen's Gambit Declined, Orthodox, Rubinstein, Main Line",
    "D66": "Queen's Gambit Declined, Orthodox, Bd3 Line",
    "D67": "Queen's Gambit Declined, Orthodox, Bd3 Line",
    "D68": "Queen's Gambit Declined, Orthodox, Classical",
    "D69": "Queen's Gambit Declined, Orthodox, Classical, Main Line",
    "D70": "Grünfeld Defence",
    "D71": "Grünfeld, Exchange",
    "D72": "Grünfeld, Neo-Grünfeld",
    "D73": "Grünfeld, Neo-Grünfeld",
    "D74": "Grünfeld, Neo-Grünfeld",
    "D75": "Grünfeld, Neo-Grünfeld",
    "D76": "Grünfeld, Neo-Grünfeld",
    "D77": "Grünfeld, Three Knights",
    "D78": "Grünfeld, Neo-Grünfeld",
    "D79": "Grünfeld, Neo-Grünfeld, 6.O-O",
    "D80": "Grünfeld Defence",
    "D81": "Grünfeld, Russian",
    "D82": "Grünfeld, 4.Bf4",
    "D83": "Grünfeld, Gambit",
    "D84": "Grünfeld, Gambit Accepted",
    "D85": "Grünfeld, Exchange",
    "D86": "Grünfeld, Exchange, Classical",
    "D87": "Grünfeld, Exchange, Spassky",
    "D88": "Grünfeld, Exchange, Spassky, Main Line",
    "D89": "Grünfeld, Exchange, Spassky, Main Line",
    "D90": "Grünfeld, Taimanov",
    "D91": "Grünfeld, Sz. Variation",
    "D92": "Grünfeld, 5.Bf4",
    "D93": "Grünfeld with 5.Bf4 d5",
    "D94": "Grünfeld, Closed",
    "D95": "Grünfeld, Pachman",
    "D96": "Grünfeld, Russian",
    "D97": "Grünfeld, Russian, Main Line",
    "D98": "Grünfeld, Russian, Main Line",
    "D99": "Grünfeld, Russian, Main Line, Smyslov",

    # E — Nimzo-Indian, Queen's Indian, King's Indian, Catalan
    "E00": "Queen's Pawn Game",
    "E01": "Catalan Opening",
    "E02": "Catalan Opening",
    "E03": "Catalan, Open",
    "E04": "Catalan, Open",
    "E05": "Catalan, Open, Classical Line",
    "E06": "Catalan, Closed",
    "E07": "Catalan, Closed",
    "E08": "Catalan, Closed",
    "E09": "Catalan, Closed, Main Line",
    "E10": "Queen's Pawn Game",
    "E11": "Bogo-Indian Defence",
    "E12": "Queen's Indian Defence",
    "E13": "Queen's Indian, 4.Nc3",
    "E14": "Queen's Indian, 4.e3",
    "E15": "Queen's Indian, Nimzovich (Exd5)",
    "E16": "Queen's Indian, Capablanca",
    "E17": "Queen's Indian, Old Main Line",
    "E18": "Queen's Indian, Old Main Line, 7.Nc3",
    "E19": "Queen's Indian, Old Main Line, 9.Qxc3",
    "E20": "Nimzo-Indian Defence",
    "E21": "Nimzo-Indian, Three Knights",
    "E22": "Nimzo-Indian, Spielmann",
    "E23": "Nimzo-Indian, Spielmann",
    "E24": "Nimzo-Indian, Sämisch",
    "E25": "Nimzo-Indian, Sämisch",
    "E26": "Nimzo-Indian, Sämisch",
    "E27": "Nimzo-Indian, Sämisch",
    "E28": "Nimzo-Indian, Sämisch, 6.e3",
    "E29": "Nimzo-Indian, Sämisch, Main Line",
    "E30": "Nimzo-Indian, Leningrad",
    "E31": "Nimzo-Indian, Leningrad, Main Line",
    "E32": "Nimzo-Indian, Classical",
    "E33": "Nimzo-Indian, Classical, Milner-Barry",
    "E34": "Nimzo-Indian, Classical, Noa",
    "E35": "Nimzo-Indian, Classical, Noa, Main Line",
    "E36": "Nimzo-Indian, Classical, Noa, Botvinnik",
    "E37": "Nimzo-Indian, Classical, Noa, Main Line, 7.Qc2",
    "E38": "Nimzo-Indian, Classical, 4...c5",
    "E39": "Nimzo-Indian, Classical, 4...c5, Main Line",
    "E40": "Nimzo-Indian, 4.e3",
    "E41": "Nimzo-Indian, 4.e3, Huebner",
    "E42": "Nimzo-Indian, 4.e3, c5, 5.Ne2",
    "E43": "Nimzo-Indian, Fischer",
    "E44": "Nimzo-Indian, Fischer, 5.Ne2",
    "E45": "Nimzo-Indian, 4.e3, Bronstein",
    "E46": "Nimzo-Indian, Reshevsky",
    "E47": "Nimzo-Indian, 4.e3 O-O, 5.Bd3",
    "E48": "Nimzo-Indian, 4.e3 O-O, 5.Bd3 d5",
    "E49": "Nimzo-Indian, 4.e3, Botvinnik",
    "E50": "Nimzo-Indian, 4.e3 e8g8, 5.Nf3",
    "E51": "Nimzo-Indian, 4.e3",
    "E52": "Nimzo-Indian, 4.e3, Main Line with ...b6",
    "E53": "Nimzo-Indian, 4.e3, Main Line",
    "E54": "Nimzo-Indian, 4.e3, Gligoric System",
    "E55": "Nimzo-Indian, 4.e3, Gligoric System, Bronstein",
    "E56": "Nimzo-Indian, 4.e3, Main Line",
    "E57": "Nimzo-Indian, 4.e3, Main Line",
    "E58": "Nimzo-Indian, 4.e3, Main Line",
    "E59": "Nimzo-Indian, 4.e3, Main Line",
    "E60": "King's Indian Defence",
    "E61": "King's Indian Defence",
    "E62": "King's Indian, Fianchetto",
    "E63": "King's Indian, Fianchetto, Panno",
    "E64": "King's Indian, Fianchetto, Yugoslav",
    "E65": "King's Indian, Fianchetto, Yugoslav, Main Line",
    "E66": "King's Indian, Fianchetto, Yugoslav, Exchange",
    "E67": "King's Indian, Fianchetto with ...Nd7",
    "E68": "King's Indian, Fianchetto, Classical",
    "E69": "King's Indian, Fianchetto, Classical, Main Line",
    "E70": "King's Indian, 4.e4",
    "E71": "King's Indian, Makogonov",
    "E72": "King's Indian with e4 & g3",
    "E73": "King's Indian, Averbakh",
    "E74": "King's Indian, Averbakh, 6...c5",
    "E75": "King's Indian, Averbakh, Main Line",
    "E76": "King's Indian, Four Pawns Attack",
    "E77": "King's Indian, Four Pawns Attack",
    "E78": "King's Indian, Four Pawns Attack, with Be2 and Nf3",
    "E79": "King's Indian, Four Pawns Attack, Main Line",
    "E80": "King's Indian, Sämisch",
    "E81": "King's Indian, Sämisch",
    "E82": "King's Indian, Sämisch, Double Fianchetto",
    "E83": "King's Indian, Sämisch",
    "E84": "King's Indian, Sämisch, Panno Main Line",
    "E85": "King's Indian, Sämisch, Orthodox",
    "E86": "King's Indian, Sämisch, Orthodox, 7.Nge2 c6",
    "E87": "King's Indian, Sämisch, Orthodox, 7.d5",
    "E88": "King's Indian, Sämisch, Orthodox, 7.d5 c6",
    "E89": "King's Indian, Sämisch, Orthodox Main Line",
    "E90": "King's Indian, 5.Nf3",
    "E91": "King's Indian, 5.Nf3",
    "E92": "King's Indian, Classical",
    "E93": "King's Indian, Petrosian System",
    "E94": "King's Indian, Orthodox",
    "E95": "King's Indian, Orthodox, 7...Nbd7, 8.Re1",
    "E96": "King's Indian, Orthodox, 7...Nbd7, Main Line",
    "E97": "King's Indian, Orthodox, Aronin-Taimanov",
    "E98": "King's Indian, Orthodox, Taimanov, 9.Ne1",
    "E99": "King's Indian, Orthodox, Taimanov, Main Line",
}


def eco_to_name(eco: str) -> str:
    """Return a human-readable opening name for an ECO code, or empty string."""
    if not eco:
        return ""
    # Try exact match first, then strip trailing variant character
    return ECO_NAMES.get(eco.strip(), ECO_NAMES.get(eco.strip()[:3], ""))


# ---------------------------------------------------------------------------
# Move-based fallback detection
# ---------------------------------------------------------------------------
_MOVE_TABLE = [
    ("e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",           "Sicilian, Najdorf"),
    ("e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 d6",           "Sicilian, Scheveningen"),
    ("e4 c5 Nf3 Nc6 d4 cxd4 Nxd4",                       "Sicilian, Classical"),
    ("e4 c5 Nf3 d6 d4 cxd4 Nxd4",                        "Sicilian, Open"),
    ("e4 c5 Nc3",                                          "Sicilian, Closed"),
    ("e4 c5",                                              "Sicilian Defence"),
    ("e4 e6 d4 d5 Nc3 Bb4",                               "French, Winawer"),
    ("e4 e6 d4 d5 Nd2",                                   "French, Tarrasch"),
    ("e4 e6 d4 d5 Nc3",                                   "French, Classical"),
    ("e4 e6",                                              "French Defence"),
    ("e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6",                    "Caro-Kann, Classical"),
    ("e4 c6 d4 d5 e5",                                     "Caro-Kann, Advance"),
    ("e4 c6",                                              "Caro-Kann Defence"),
    ("e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3",  "Ruy Lopez, Closed"),
    ("e4 e5 Nf3 Nc6 Bb5 a6 Ba4",                          "Ruy Lopez, Morphy"),
    ("e4 e5 Nf3 Nc6 Bb5",                                 "Ruy Lopez"),
    ("e4 e5 Nf3 Nc6 Bc4 Bc5 b4",                          "Italian, Evans Gambit"),
    ("e4 e5 Nf3 Nc6 Bc4 Bc5 c3",                          "Italian, Giuoco Piano"),
    ("e4 e5 Nf3 Nc6 Bc4 Nf6",                             "Italian, Two Knights"),
    ("e4 e5 Nf3 Nc6 Bc4",                                 "Italian Game"),
    ("e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6",              "Scotch, Mieses"),
    ("e4 e5 Nf3 Nc6 d4",                                  "Scotch Game"),
    ("e4 e5 f4 exf4 Nf3",                                 "King's Gambit Accepted"),
    ("e4 e5 f4",                                           "King's Gambit"),
    ("e4 e5 Nf3 Nf6",                                     "Petrov's Defence"),
    ("e4 e5 Nf3 Nc6",                                     "Open Game"),
    ("e4 e5",                                              "Open Game"),
    ("d4 d5 c4 e6 Nc3 Nf6 Bg5",                           "Queen's Gambit, Orthodox"),
    ("d4 d5 c4 dxc4",                                     "Queen's Gambit Accepted"),
    ("d4 d5 c4 e6",                                       "Queen's Gambit Declined"),
    ("d4 d5 c4",                                           "Queen's Gambit"),
    ("d4 Nf6 c4 g6 Nc3 Bg7 e4 d6",                        "King's Indian Defence"),
    ("d4 Nf6 c4 e6 Nc3 Bb4",                              "Nimzo-Indian Defence"),
    ("d4 Nf6 c4 e6 Nf3 b6",                               "Queen's Indian Defence"),
    ("d4 Nf6 c4 g6 Nc3 d5",                               "Grünfeld Defence"),
    ("d4 f5",                                              "Dutch Defence"),
    ("c4 e5",                                              "English, Reversed Sicilian"),
    ("c4",                                                 "English Opening"),
    ("d4 Nf6 Nf3 e6 Bf4",                                 "London System"),
    ("d4 d5 Nf3 Nf6 e3 e6 Bd3",                           "Colle System"),
    ("d4 Nf6 c4",                                         "Indian Defence"),
    ("d4 d5",                                              "Closed Game"),
    ("d4",                                                 "Queen's Pawn Opening"),
    ("e4",                                                 "King's Pawn Opening"),
]


def detect_from_moves(game: chess.pgn.Game) -> str:
    """Walk up to 18 half-moves and return the best opening match."""
    board = game.board()
    sans: list[str] = []
    for move in game.mainline_moves():
        sans.append(board.san(move))
        board.push(move)
        if len(sans) >= 18:
            break
    move_str = " ".join(sans)
    for prefix, name in _MOVE_TABLE:
        if move_str.startswith(prefix):
            return name
    return ""


def resolve_opening(game: chess.pgn.Game) -> tuple[str, str]:
    """
    Return (opening_name, eco) for a game, using PGN headers first then
    falling back to ECO lookup and move detection.
    """
    headers = game.headers
    opening = headers.get("Opening", "").strip()
    eco     = headers.get("ECO", "").strip()

    if not opening and eco:
        opening = eco_to_name(eco)
    if not opening:
        opening = detect_from_moves(game)

    return opening, eco
